version: '2.1'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: xrparrot/internal-api
    restart: always
    container_name: xrparrot-api
    command: [ "--env", "production" ]
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    # environment:
      # PORT: 3000 # also available in pm2 "PORT"
      # MODE: "production" # also available in pm2 "NODE_ENV"
      # MONGO: "mongo:27017/xrparrot" # either set here or in nodemon config in package.json
    links:
      - mongo
  mongo:
    image: mongo:latest
    restart: always
    container_name: xrparrot-mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./db:/data/db
    ports:
      - 20000:27017
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/xrpl
      interval: 5s
      timeout: 5s
      retries: 5
    command: mongod --smallfiles --logpath=/dev/null # --quiet
